name: clang-tidy-review
on:
  push:
    paths:
      - 'cpp/**'
    branches:
      - main
  pull_request:
    paths:
      - 'cpp/**'
  workflow_dispatch:
permissions:
  contents: read
  # Optional: Allow read access to pull request. Use with `only-new-issues` option.
  pull-requests: write
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: .github/cpp-linter
      id: review
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
