name: Lint Bash
on:
  pull_request:
    branches: [main]
    paths:
      - "aws-cli/**"
  workflow_dispatch:
jobs:
  sh-checker:
    name: Lint Bash
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Lint Bash
        uses: luizm/action-sh-checker@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          sh_checker_comment: true