name: Validate Documentation Metadata
on:
  pull_request:
  # run on demand
  workflow_dispatch:
jobs:
  validate-doc-metadata:
    runs-on: ubuntu-latest
    steps:
      - name: Pass
        run: true
